import type { Metadata } from 'next';
import { BRAND } from '@/config/brand';
import { LegalPage, type LegalSection } from '@/components/landing/LegalPage';

export const metadata: Metadata = {
  title: `Accessibility and ADA · ${BRAND.name}`,
  description: `How ${BRAND.legalName} works to keep its workforce portal usable by everyone, and how to report a barrier.`,
};

const sections: LegalSection[] = [
  {
    id: 'commitment',
    heading: 'Our commitment',
    body: [
      `${BRAND.legalName} works to make this portal usable by everyone on the team, including people who use screen readers, keyboard navigation, magnification, or other assistive technology.`,
      'We aim to meet the Web Content Accessibility Guidelines (WCAG) 2.1 at Level AA, and we treat accessibility as part of building a feature rather than something added afterwards. Where the Americans with Disabilities Act applies to us as an employer, an employee who needs an accommodation to use this system should not have to fight for it.',
    ],
  },
  {
    id: 'what-we-do',
    heading: 'What is in place',
    points: [
      'Every interactive control can be reached and operated with a keyboard, and the focused element is always visibly marked.',
      'Tables, forms and dialogs carry the labels and roles assistive technology needs, and dialogs keep focus inside them until closed.',
      'Text meets the AA contrast ratio against its background, and colour is never the only way information is conveyed. Statuses carry words as well as colour.',
      'The interface scales with your screen and with browser zoom, so text can be enlarged without breaking the layout or losing content.',
      'Animation is decorative and brief, and it is switched off automatically when your system asks for reduced motion.',
      'Images carry alternative text, and decorative images are hidden from assistive technology instead of being announced as noise.',
      'Errors say what went wrong and how to fix it, in text, next to the field they concern.',
    ],
  },
  {
    id: 'limitations',
    heading: 'Known limitations',
    body: [
      'We are honest about where we are not there yet.',
    ],
    points: [
      'Some data tables are wide and scroll sideways on small screens. The content is reachable, but reading it on a phone is harder than it should be.',
      'Documents uploaded to the portal, such as scanned letters or certificates, are only as accessible as the file that was uploaded. We cannot retrofit a scan.',
      'Printed and PDF reports generated by the portal are laid out for print and are not tuned for screen readers.',
    ],
  },
  {
    id: 'accommodations',
    heading: 'Asking for an accommodation',
    body: [
      'If any part of this portal is a barrier to doing your job, tell us and we will find another way to get you what you need, whether that is a change to the system, an alternative format, or a person who will do the task with you.',
      'Asking costs you nothing and does not need to go through a formal process first.',
    ],
  },
  {
    id: 'report',
    heading: 'Reporting a barrier',
    body: [
      `Email HR at ${BRAND.contactEmail} with what you were trying to do, the page you were on, and the assistive technology or browser you use. That last detail is usually what lets us reproduce the problem quickly.`,
      'We aim to acknowledge reports within two working days and to tell you what we are going to do about it, including a timeframe when a fix is not immediate.',
    ],
  },
  {
    id: 'assessment',
    heading: 'How we check',
    body: [
      'Accessibility is reviewed as part of building and changing the portal, using a combination of keyboard and screen reader testing, automated checks, and contrast verification against the design tokens the interface is built from.',
      'This statement is reviewed as the portal changes. If you find it out of date, that is worth reporting too.',
    ],
  },
];

export default function AccessibilityPage() {
  return (
    <LegalPage
      eyebrow="Accessibility"
      title="Accessibility and ADA"
      intro="What we do to keep this portal usable by everyone, where we fall short, and how to tell us when something gets in your way."
      updated="August 2026"
      sections={sections}
    />
  );
}
